// launchkit — gym template (auto-generated by extract.js)
// Source: /tmp/mrbig
// Extracted: 2026-03-23

const { copyTemplateFiles, replaceInFile } = require("../lib");
const lib = require("../lib");

const TYPE = "gym";
const DESCRIPTION = "Gym — extracted template";
const DETECTED_COLOR = "indigo";

const COLOR_MAP = ["indigo", "blue", "violet", "rose", "amber", "emerald", "cyan", "orange", "teal", "sky", "red", "green"];
const COLOR_LABELS = ["Indigo", "Blue", "Violet", "Rose", "Amber", "Emerald", "Cyan", "Orange", "Teal", "Sky", "Red", "Green"];

// Extra dependencies beyond base scaffold
const EXTRA_DEPS = {
  "@vercel/analytics": "^1.6.1",
  "@vercel/speed-insights": "^1.3.1"
};

function recolor(fromColor, toColor, compDir, layoutFile) {
  const { target } = require("../lib");
  const fs = require("fs");
  const path = require("path");
  const absCompDir = path.join(target(), compDir);
  if (!fs.existsSync(absCompDir)) return;
  // Walk all .tsx files (flat or in subdirectories)
  function walkTsx(dir, rel) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const entryRel = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walkTsx(path.join(dir, entry.name), entryRel);
      } else if (entry.name.endsWith(".tsx")) {
        replaceInFile(path.join(compDir, entryRel), `${fromColor}-`, `${toColor}-`);
      }
    }
  }
  walkTsx(absCompDir, "");
  // Also recolor layout
  replaceInFile(layoutFile, `${fromColor}-`, `${toColor}-`);
}

async function setup(rl, answers) {
  const { askChoice } = require("../lib");

  let accentColor;
  if (answers?.accentColor && COLOR_MAP.includes(answers.accentColor)) {
    accentColor = answers.accentColor;
  } else {
    const colorChoice = await askChoice(rl, "Brand accent color?", COLOR_LABELS);
    accentColor = COLOR_MAP[(colorChoice ?? 1) - 1];
  }

  copyTemplateFiles(TYPE);

  // Add extra dependencies
  for (const [dep, ver] of Object.entries(EXTRA_DEPS)) {
    lib.addDependency(dep, ver);
  }

  if (accentColor !== DETECTED_COLOR) {
    const i18nActive = require("fs").existsSync(require("path").join(lib.target(), "i18n-config.ts"));
    const compDir = i18nActive ? "app/[locale]/components" : "app/components";
    const layoutFile = i18nActive ? "app/[locale]/layout.tsx" : "app/layout.tsx";
    recolor(DETECTED_COLOR, accentColor, compDir, layoutFile);
  }

  return { type: TYPE, features: { accentColor }, sections: {} };
}

module.exports = { type: TYPE, description: DESCRIPTION, setup, recolor, COLOR_MAP, COLOR_LABELS };
