// launchkit — restaurant template (auto-generated by extract.js)
// Source: /home/sebas/dev/projects/gutsy
// Extracted: 2026-03-23

const { copyTemplateFiles, replaceInFile } = require("../lib");
const lib = require("../lib");

const TYPE = "restaurant";
const DESCRIPTION = "Restaurant — extracted template";
const DETECTED_COLOR = "orange";

const COLOR_MAP = ["indigo", "blue", "violet", "rose", "amber", "emerald", "cyan", "orange", "teal", "sky", "red", "green"];
const COLOR_LABELS = ["Indigo", "Blue", "Violet", "Rose", "Amber", "Emerald", "Cyan", "Orange", "Teal", "Sky", "Red", "Green"];

// Extra dependencies beyond base scaffold
const EXTRA_DEPS = {
  "resend": "^6.9.4"
};

function recolor(fromColor, toColor, compDir, layoutFile) {
  const { target } = require("../lib");
  const fs = require("fs");
  const path = require("path");
  const absCompDir = path.join(target(), compDir);
  if (!fs.existsSync(absCompDir)) return;
  const files = fs.readdirSync(absCompDir).filter((f) => f.endsWith(".tsx"));
  for (const file of files) {
    replaceInFile(path.join(compDir, file), `${fromColor}-`, `${toColor}-`);
  }
  // Also recolor layout
  replaceInFile(layoutFile, `${fromColor}-`, `${toColor}-`);
}

async function setup(rl, answers) {
  const { askChoice } = require("../lib");

  let accentColor;
  if (answers?.accentColor && COLOR_MAP.includes(answers.accentColor)) {
    accentColor = answers.accentColor;
  } else {
    const colorChoice = await askChoice(rl, "Brand accent color?", COLOR_LABELS);
    accentColor = COLOR_MAP[(colorChoice ?? 1) - 1];
  }

  copyTemplateFiles(TYPE);

  // Add extra dependencies
  for (const [dep, ver] of Object.entries(EXTRA_DEPS)) {
    lib.addDependency(dep, ver);
  }

  if (accentColor !== DETECTED_COLOR) {
    const i18nActive = require("fs").existsSync(require("path").join(lib.target(), "i18n-config.ts"));
    const compDir = i18nActive ? "app/[locale]/components" : "app/components";
    const layoutFile = i18nActive ? "app/[locale]/layout.tsx" : "app/layout.tsx";
    recolor(DETECTED_COLOR, accentColor, compDir, layoutFile);
  }

  return { type: TYPE, features: { accentColor }, sections: {} };
}

module.exports = { type: TYPE, description: DESCRIPTION, setup, recolor, COLOR_MAP, COLOR_LABELS };
